stages:
  - test

test gudel-cmm-frontend:
  stage: test
  image: elunic/node-angular-chrome:node12-angular9
  script:
    - "npm ci --unsafe"
    - "npm run test:ci"
    - "echo Overall code coverage: $(cat ./coverage/coverage-summary.json | jq '.total | map(.pct) | add/length') %"
  coverage: '/Overall code coverage: ([\d.]+) %/'
  artifacts:
    name: "$CI_JOB_NAME-$CI_COMMIT_REF_SLUG"
    reports:
      junit: test-reports/*.xml
    paths:
      - coverage/
      - test-reports/
